[project]
name = "ideas-neural-circuit-analysis"
description = "IDEAS Neural Circuit Analysis Toolkit"
requires-python = "==3.13.12"
classifiers = [
    "Programming Language :: Python :: 3"
]
dependencies = []

dynamic = ["version"]

[tool.setuptools.packages.find]
exclude = ["data", "inputs", "resources"]

[dependency-groups]
analysis = [
    "ideas-python[analysis]==1.1.1",
    "numpy==2.2.6",
    "pandas==2.3.3",
    "scipy==1.16.3",
    "scikit-learn==1.7.2",
    "scikit-image==0.25.2",
    "pingouin==0.5.5",
    "opencv-python==4.12.0.88",
    "statsmodels==0.14.5",
    "matplotlib==3.10.7",
    "plotly==6.5.0",
    "seaborn==0.13.2",
    "bokeh==3.8.1",
    "pyarrow==22.0.0",
    "h5py==3.15.1",
    "tifffile==2025.10.16",
    "imageio==2.37.2",
    "imageio-ffmpeg==0.6.0",
    "Pillow==12.0.0",
    "isx==2.1.0",
    "pynwb==3.1.2",
    "pynapple==0.10.1",
    "beartype==0.22.6",
]
test = [
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "pytest-order",
    "pytest-watch",
]
dev = [
    "pre-commit",
    "ruff==0.11.4",
]

[tool.uv]
package = false

[tool.pytest.ini_options]
pythonpath = [
  "."
]

[tool.ruff]
# flake8-builtins (A)
# pycodestyle errors (E) and warnings (W)
# pyflakes (F)
# isort (I)
lint.select = ["A", "E", "W", "F", "I"]
show-fixes = true
line-length = 88
# Be permissive of long lines
lint.ignore = ["E501", "A005"]
target-version = "py313"
extend-exclude = ["venv", "venv_test", "venv3", ".venv"]

[tool.ruff.lint.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[tool.pydocstyle]
add-ignore = ["D104"]  # ignore missing package docstring to reduce noise
