import logging
import os

import numpy as np
import pandas as pd
from beartype import beartype
from beartype.typing import List, Optional
from ideas.analysis import io
from ideas.exceptions import IdeasError
from ideas.analysis.utils import _extract_footer, get_file_size
from ideas.analysis.validation import cell_set_series, movie_series, _check_columns_in_df
from ideas.analysis.metadata import read_isxd_metadata
from ideas.tools.types import IdeasFile
from pandas.api.types import (
    is_float_dtype,
    is_integer_dtype,
    is_numeric_dtype,
    is_string_dtype,
)
import isx

from utils.utils import (
    _save_experiment_annotations_preview_and_metadata,
)

logger = logging.getLogger()

# constants
HARDWARE_COUNTER_TIME_COLUMN = "Hardware counter (us)"
ALIGNMENT_METHOD_COLUMN = "alignment method"
HARDWARE_TSC_ALIGNMENT_METHOD = "hardware_tsc"
START_TIME_ALIGNMENT_METHOD = "start_time"

PARQUET_FILENAME = "annotations.parquet"
PARQUET_PREVIEW_FILENAME = "annotations_preview.svg"


def _get_isxd_times(input_filename):
    """Get the timestamps of every sample of an isxd file from its metadata.

    The timestamps are generated by getting the average sampling period
    of the isxd file.

    :param input_filename str: path to the input file (.isxd)
    :return: The timestamps of every sample in the isxd file
    """
    metadata = _extract_footer(input_filename)
    period = (
        metadata["timingInfo"]["period"]["num"]
        / metadata["timingInfo"]["period"]["den"]
    )
    num_times = metadata["timingInfo"]["numTimes"]
    times = np.linspace(
        0,
        (num_times - 1) * period,
        num_times,
    )
    return times


def _get_start_tsc_from_isxd_metadata(input_filename):
    """Get the first hardware tsc value from the metadata of an isxd file.

    This metadata is written during IDPS processing.
    It can be used to align with synchronized isxb data.

    :param input_filename str: path to the input file (.isxd)
    :return: The start tsc of the isxd file
    """
    start_tsc = _peek_start_tsc_from_isxd_metadata(input_filename)
    if start_tsc is None:
        raise IdeasError(
            "Could not find startTsc metadata in the input ISXD file "
            f"`{os.path.basename(input_filename)}`. "
            "This alignment method requires IDPS metadata in "
            "`extraProperties.startTsc` when the annotations include "
            f"`{HARDWARE_COUNTER_TIME_COLUMN}`. "
            "Alternatively, align by epoch start time by setting "
            "`use_hardware_tsc_alignment` to `False`."
        )

    return start_tsc


def _peek_start_tsc_from_isxd_metadata(input_filename):
    """Get startTsc from an isxd file metadata if available.

    :param input_filename str: path to the input file (.isxd)
    :return: startTsc value or None when not available.
    """
    metadata = _extract_footer(input_filename)
    extra_properties = metadata.get("extraProperties")
    if not isinstance(extra_properties, dict):
        return None
    return extra_properties.get("startTsc")


def _get_alignment_method_and_start_tsc(
    *,
    annotations_df: pd.DataFrame,
    isxd_file_for_tsc: str,
    use_hardware_tsc_alignment: bool,
):
    """Get alignment method and start tsc for an annotations dataframe."""
    if HARDWARE_COUNTER_TIME_COLUMN not in annotations_df.columns:
        logger.info("No hardware tsc column detected in annotations.")
        return START_TIME_ALIGNMENT_METHOD, None

    if not use_hardware_tsc_alignment:
        logger.warning(
            "Ignoring hardware tsc column and using start-time alignment "
            "because `use_hardware_tsc_alignment` is set to False."
        )
        return START_TIME_ALIGNMENT_METHOD, None

    start_tsc = _get_start_tsc_from_isxd_metadata(isxd_file_for_tsc)
    return HARDWARE_TSC_ALIGNMENT_METHOD, start_tsc


def _get_start_time_from_isxd_metadata(input_filename):
    """Get the epoch start time from the metadata of an isxd file.

    :param input_filename str: path to the input file (.isxd)
    :return: The epoch start time of the isxd file
    """
    metadata = _extract_footer(input_filename)
    return (
        metadata["timingInfo"]["start"]["secsSinceEpoch"]["num"]
        / metadata["timingInfo"]["start"]["secsSinceEpoch"]["den"]
    )


def _map_defined_values_to_col(
    mapped_frames: pd.Series, df: pd.DataFrame, column_name: str
) -> pd.Series:
    """Map defined values in an annotations dataframe to a new column.
    This handles nan values for mapped frames, i.e., no mapped frame exists.

    :param mapped_frames pd.Series: Indices of the frames to map from the
        input annotations to the isxd data.
    :param df pd.DataFrame: The input annotations.
    :param column_name str: The name of the column the input annotations to
        map to the isxd data.

    :return column: Column with mapped values.
    """
    # determine undefined values for every possible dtype
    if is_integer_dtype(df[column_name].dtype):
        val = np.nan
        dtype = pd.Int64Dtype()
    elif is_float_dtype(df[column_name].dtype):
        val = np.nan
        dtype = float
    elif is_string_dtype(df[column_name].dtype):
        val = ""
        dtype = str
    else:
        raise IdeasError(
            f"Unknown dtype ({df[column_name].dtype}) for input column ({column_name})."
        )

    # initialize column with undefined values
    column = pd.Series(
        val, index=np.arange(len(mapped_frames)), dtype=dtype, name=column_name
    )

    # set all defined values in column
    valid_idx = mapped_frames.loc[~mapped_frames.isna()]
    column[valid_idx.index] = df.iloc[valid_idx][column_name]
    return column


def _map_frames(
    ref_recordings_times: List[pd.Series],
    align_recordings_times: List[pd.Series],
    ref_epoch_start_times: List[int],
    align_epoch_start_times: List[int],
):
    """Map frames from an align dataset timeline to a reference
    dataset timeline.
    This is meant to map annotations frames to isxd data.

    :param ref_recordings_times List[pd.Series]:
        Timestamps for a series of recordings to use a as a reference timeline
        for mapping frames.
    :param align_recordings_times List[pd.Series]:
        Timestamps for a series of
        recordings to align to a reference timeline for mapping frames.
    :param ref_epoch_start_times List[int]: List of epoch start timestamps
        for every recording in `ref_recordings_times`.
        This is used to add time delays
        between recordings in `ref_recordings_times` so that
        timestamps are relative
        to the start of the experiment. This is also used to
        determine time delays
        between the start of the experiment and the recordings of `align_recordings_times`.
    :param align_epoch_start_times List[int]: List of epoch start timestamps
        for every recording of `align_recordings_times`. This is used to add time delays
        between recordings in `align_recordings_times` so that timestamps are relative
        to the start of the experiment.

    :return ref_times, align_times, mapped_align_frames: Three pandas Series objects.
        `ref_times` contains the combined timestamps of all reference recordings,
        with timestamps adjusted to factor in time delays between recordings.
        `align_times` contains the combined timestamps of all align recordings,
        with timestamps adjusted to factor in time delays between recordings and
        the start of the refernce recordings.
        `mapped_align_frames` contains the frames in `align_times` that map to
        every frame in `ref_times`,
    """
    # check lengths of input vectors
    assert len(ref_recordings_times) == len(ref_epoch_start_times)
    assert len(align_recordings_times) == len(align_epoch_start_times)

    # factor in time delays between reference recordings
    ref_time_offsets = [0.0]
    ref_times = []
    for i, ref_epoch_start_time in enumerate(ref_epoch_start_times):
        if i > 0:
            ref_time_offsets.append(
                ref_time_offsets[-1]
                + (ref_epoch_start_time - ref_epoch_start_times[i - 1])
            )

        ref_times.append(ref_recordings_times[i] + ref_time_offsets[-1])

    # factor in time delays between align recordings
    align_times = []
    for i, align_epoch_start_time in enumerate(align_epoch_start_times):
        time_offset = align_epoch_start_time - ref_epoch_start_times[0]
        align_times.append(align_recordings_times[i] + time_offset)

    # join all the adjusted recording times into one vector
    ref_times = pd.concat(ref_times, ignore_index=True)
    align_times = pd.concat(align_times, ignore_index=True)

    # find the closest align time for every ref time
    align_frames = np.arange(len(align_times))
    mapped_align_frames = pd.Series(
        np.interp(ref_times, align_times, align_frames).round()
    )

    # compute the average sampling period of the align times
    # this will be used as a threshold for the max time difference between a
    # reference frame and the mapped align frame
    align_average_sample_period = np.mean(
        [
            np.mean(align_recording_times.diff())
            for align_recording_times in align_recordings_times
        ]
    )

    for i, (mapped_align_frame, ref_time) in enumerate(
        zip(mapped_align_frames, ref_times)
    ):
        if np.isnan(mapped_align_frame):
            logger.warning(
                f"Found nan mapped frame at index {i}, and ref time {ref_time}, skipping validation checks"
            )
            continue

        align_time = align_times[mapped_align_frame]

        # verify the time difference between the reference frame and the mapped align frame
        # is no bigger than the align average sample period
        # otherwise set the mapped frame to nan
        if abs(align_time - ref_time) > align_average_sample_period:
            mapped_align_frames.iloc[i] = np.nan

    return ref_times, align_times, mapped_align_frames


@beartype
def sync_csv_to_annotations(
    *,
    isxd_files: List[IdeasFile],
    annotations_files: List[IdeasFile],
    time_column: str = "time",
    state_column: str = "state",
    gpio_ref_file: Optional[List[IdeasFile]] = None,
    gpio_ref_channel: Optional[str] = None,
    gpio_ref_threshold: Optional[int] = None,
    manual_time_offset: Optional[float] = None,
    use_hardware_tsc_alignment: bool = True,
) -> None:
    """Map frames in experiment annotations to frames
    in ISXD data. This maps the closest points in the
    annotations to time points in the isxd data and.

    :param isxd_files List[str]: The isxd files to map frames to.
        Can be either a series of movies or cell sets.
    :param annotations_files List[str]: The annotations files to map
        frames from. Can be either a series of parquet or csv files.
    :param time_column str: The name of the time column in the
        annotations files to use for mapping.
    :param state_column str: The name of the state column in the
        annotations files to map to the isxd data.
    :param gpio_ref_file Optional[List[str]]: Gpio file to use
    as time-reference for the input annotations.
        A time offset is automatically computed
        between the gpio file and the input isxd files from the <gpio_ref_channel>.
        This time offset is used to align the input annotations to the input isxd files.
        Only applicable for third-party annotations.
    :param gpio_ref_channel Optional[str]: Specifies the channel to
    automatically compute the time offset if a gpio file is provided as time-reference.
        The channel name must be present in the gpio file.
    :param gpio_ref_threshold Optional[int]: If a gpio file
    is provided as a time-reference, this parameter specifies an optional threshold to
        apply on the gpio reference channel.
        The time offset will be computed from the first sample
        in the channel which is greater than
        or equal to the threshold. If empty, use the timestamp of
        the first sample in the channel to compute the time offset.
    :param manual_time_offset Optional[float]:
    Specifies a time offset to manually set between the input annotations and the input isxd files.
    :param use_hardware_tsc_alignment bool:
    Whether to align annotations using hardware tsc metadata when
    `Hardware counter (us)` is available in input annotations.
    If enabled and startTsc metadata is missing in the reference ISXD,
    this tool raises an error.
    """
    logger.info("Mapping annotations to ISXD data...")

    logger.info("Sorting input files by name.")
    # check whether isxd movie or cell set
    try:
        isxd_files = movie_series(isxd_files)
    except Exception as e:
        if "Expected data set to be of type: Movie" in str(e):
            isxd_files = cell_set_series(isxd_files)
        else:
            raise e

    # ensure that the number of isxd files and annotations files match,
    # or that a single annotations file is provided
    if (
        len(isxd_files) != len(annotations_files)
        and len(annotations_files) != 1
    ):
        raise IdeasError(
            "Expected to get the same number of isxd files and annotations,"
            "or a single annotations file."
            f"Instead, received {len(isxd_files)} isxd files"
            f" and {len(annotations_files)} annotations files"
        )

    # track the epoch start times of isxd data, annotations data will be
    # re-aligned according to this
    logger.info("Reading epoch start times from isxd files.")
    isxd_epoch_start_times = [
        _get_start_time_from_isxd_metadata(isxd_file)
        for isxd_file in isxd_files
    ]
    logger.info(
        f"Read the following epoch start times from the isxd files: {isxd_epoch_start_times}"
    )

    # read in state-based annotations file
    all_df = []
    annotations_epoch_start_times = []
    alignment_methods = []
    for i, annotations_file in enumerate(annotations_files):
        # support either parquet or csv for input annotations
        logger.info(f"Reading input annotations file: {annotations_file}")
        if annotations_file.endswith(".parquet"):
            df = pd.read_parquet(annotations_file)
        elif annotations_file.endswith(".csv"):
            df = pd.read_csv(annotations_file)
        else:
            raise AssertionError(
                f"Annotations file ({annotations_file}) not of expected formats (.csv, .parquet)"
            )

        # check input columns are in df
        logger.info(
            f"Checking input time and state columns ({time_column},"
            f" {state_column}) are in the input annotations."
        )
        _check_columns_in_df(
            df=df,
            columns=(time_column, state_column),
        )

        # check that the state_column is not numeric
        logger.info("Checking state column is not numeric.")
        if is_numeric_dtype(df[state_column]):
            raise IdeasError(
                f"The values in the `{state_column}` "
                f"column of the input CSV file `{os.path.basename(annotations_file)}`"
                " are convertible to a numeric type. This is not allowed."
                " This tool expects values to be categorical. ",
            )

        logger.info(
            "Checking if annotations have hardware tsc column to use to align with isxd data."
        )
        has_hardware_tsc_column = HARDWARE_COUNTER_TIME_COLUMN in df.columns
        apply_hardware_tsc_alignment = (
            has_hardware_tsc_column and use_hardware_tsc_alignment
        )
        alignment_method = START_TIME_ALIGNMENT_METHOD
        if apply_hardware_tsc_alignment:
            # annotations are coming from an .isxb file that is synchronized to the input isxd data
            # the epoch start time of the .isxb files need to be aligned to isxd data
            logger.info(
                "Detected hardware tsc column in annotations."
                "Computing epoch start time of annotations based on tsc offset from isxd."
            )

            if len(isxd_files) == len(annotations_files):
                # equal number of isxd and annotation files, assume longitudinal recording
                # get corresponding isxd file and use as reference
                logger.info(
                    "Equal number of isxd and annotation files,"
                    "assuming a longitudinal recording."
                    "Aligning annotations epoch start time to corresponding isxd file."
                )
                isxd_epoch_start_time = isxd_epoch_start_times[i]
                isxd_file_for_tsc = isxd_files[i]
            else:
                # unequal number of isxd and annotation files, align all annotations to first isxd
                logger.info(
                    "Unequal number of isxd and annotation files."
                    "Aligning annotations epoch start time to first isxd file."
                )
                isxd_epoch_start_time = isxd_epoch_start_times[0]
                isxd_file_for_tsc = isxd_files[0]

            (
                alignment_method,
                isxd_start_tsc,
            ) = _get_alignment_method_and_start_tsc(
                annotations_df=df,
                isxd_file_for_tsc=isxd_file_for_tsc,
                use_hardware_tsc_alignment=use_hardware_tsc_alignment,
            )
            # calculate tsc offset
            annotations_start_tsc = df.iloc[0][HARDWARE_COUNTER_TIME_COLUMN]
            tsc_offset = (annotations_start_tsc - isxd_start_tsc) / 1e6
            logger.info(
                "Aligning annotations with start tsc"
                f"({annotations_start_tsc} us) to isxd file with start tsc"
                f" ({isxd_start_tsc} us) and epoch start time ({isxd_epoch_start_time} s)"
            )

            # calculate epoch start time of annotations based on tsc offset
            annotations_epoch_start_time = isxd_epoch_start_time + tsc_offset
            logger.info(
                f"Tsc offset is ({tsc_offset} s)."
                " Aligned epoch start time of annotations is "
                f"({annotations_epoch_start_time} s)"
            )

        if not apply_hardware_tsc_alignment:
            # no tsc values
            if has_hardware_tsc_column and not use_hardware_tsc_alignment:
                logger.info(
                    "Using start-time alignment and ignoring hardware tsc column."
                )
            elif not has_hardware_tsc_column:
                logger.info("No hardware tsc column detected in annotations.")

            # time offset can optionally be computed for third-party annotations
            # this is added to the epoch start time of the annotation files
            time_offset = 0.0

            if manual_time_offset is not None:
                time_offset = manual_time_offset
                logger.info(
                    f"Using manual time offset of {manual_time_offset}"
                    " to align third-party annotations to input isxd files"
                )
            elif gpio_ref_file is not None:
                logger.info(
                    "Using input gpio file as time reference for input annotations"
                )

                if gpio_ref_channel is None:
                    raise IdeasError(
                        "Must provide channel name with gpio time reference file"
                    )

                if len(gpio_ref_file) != 1:
                    raise IdeasError(
                        "Single gpio time reference file must be provided"
                    )
                gpio_ref_file = gpio_ref_file[0]

                # export gpio file to isxd format
                if gpio_ref_file.lower().endswith(".gpio"):
                    logger.info("Exporting .gpio file to .isxd format")
                    output_dir = os.getcwd()
                    isx.export_gpio_to_isxd(gpio_ref_file, output_dir)
                    fname = os.path.splitext(os.path.basename(gpio_ref_file))[
                        0
                    ]
                    gpio_ref_file = f"{fname}_gpio.isxd"

                # read gpio file
                gpio = isx.GpioSet.read(gpio_ref_file)
                gpio_channels = gpio.channel_dict.keys()
                logger.info(
                    f"Gpio file has the following channels: {gpio_channels}"
                )

                # try to get values for channel
                if gpio_ref_channel not in gpio_channels:
                    raise IdeasError(
                        f"Could not find channel {gpio_ref_channel} in input gpio file"
                    )
                gpio_ref_channel_index = gpio.channel_dict[gpio_ref_channel]
                logger.info(
                    f"Found channel {gpio_ref_channel} in"
                    f" input gpio file with index {gpio_ref_channel_index}"
                )

                # find first value in channel trace
                [
                    gpio_ref_channel_offsets,
                    gpio_ref_channel_amps,
                ] = gpio.get_channel_data(gpio_ref_channel_index)
                if gpio_ref_threshold is None:
                    gpio_ref_time_start = gpio_ref_channel_offsets[0]
                    logger.info(
                        f"Using first timestamp ({gpio_ref_time_start} s)"
                        " of channel as reference for annotation"
                    )
                else:
                    x = 0
                    while gpio_ref_channel_amps[x] < gpio_ref_threshold:
                        x += 1
                        if x == len(gpio_ref_channel_amps):
                            raise IdeasError(
                                "Unable to find timestamp in input gpio "
                                f"channel {gpio_ref_channel} with a value greater "
                                f"than or equal to {gpio_ref_threshold}"
                            )
                    gpio_ref_time_start = gpio_ref_channel_offsets[x]
                    logger.info(
                        f"Found timestamp ({gpio_ref_time_start} s) in channel trace at sample {x}"
                    )

                # get tsc value from gpio file metadata
                logger.info(
                    "Reading metadata from input gpio ref file to get start tsc"
                )
                gpio_md = read_isxd_metadata(gpio_ref_file)
                gpio_extra_properties = gpio_md.get("extraProperties")
                gpio_first_tsc = (
                    gpio_extra_properties.get("firstTsc")
                    if isinstance(gpio_extra_properties, dict)
                    else None
                )
                if gpio_first_tsc is None:
                    raise IdeasError(
                        "Failed to find first tsc in input gpio file metadata"
                    )

                isxd_start_tsc = _get_start_tsc_from_isxd_metadata(
                    isxd_files[0]
                )
                logger.info(
                    "Extracted first tsc from gpio file footer:"
                    f" {gpio_first_tsc}, and first tsc from"
                    f" isxd file footer: {isxd_start_tsc}"
                )

                # compute time offset between gpio tsc and isxd tsc + time offset of
                # channel signal from start of gpio
                time_offset = float(gpio_first_tsc - isxd_start_tsc) / 1e6
                logger.info(
                    f"Computed time offset of {time_offset} s between"
                    " input gpio file and the first input isxd file"
                )

                time_offset += float(gpio_ref_time_start) / 1e6
                logger.info(
                    f"Computed {time_offset} s between input gpio"
                    " reference channel and the first input isxd file."
                    " Using this to align third-party annotations to input isxd files"
                )

            if len(isxd_files) == len(annotations_files):
                # equal number of isxd and annotation files, assume longitudinal recording
                # get corresponding isxd file and use as reference
                annotations_epoch_start_time = (
                    isxd_epoch_start_times[i] + time_offset
                )
                logger.info(
                    "Equal number of isxd and annotation files,"
                    " assuming a longitduinal recording. Set annotations"
                    " to start at the same time as the corresponding isxd file"
                    f" ({annotations_epoch_start_time} s)."
                )
            else:
                # unequal number of isxd and annotation files, align all annotations to first isxd
                logger.info(
                    "Unequal number of isxd and annotation files."
                    "Aligning annotations epoch start time to first isxd file."
                )
                current_duration = (
                    np.sum(
                        [
                            df[time_column].diff().iloc[1:].sum()
                            for df in all_df
                        ]
                    )
                    if all_df
                    else 0.0
                )
                annotations_epoch_start_time = (
                    isxd_epoch_start_times[0] + time_offset + current_duration
                )
                logger.info(
                    f"The current, cumulative duration "
                    f"of previous annotation files is ({current_duration} s), "
                    "set this annotations file to start right after the previous one "
                    f"({annotations_epoch_start_time} s)"
                )

        annotations_epoch_start_times.append(annotations_epoch_start_time)
        alignment_methods.append(alignment_method)
        all_df.append(df)

    # construct vector of isxd and annotation times for every input file
    isxd_recordings_times = [
        pd.Series(_get_isxd_times(cell_set_file))
        for cell_set_file in isxd_files
    ]
    annotations_recordings_times = [df[time_column] for df in all_df]

    # map frames from annotations to isxd
    logger.info("Mapping annotations frames to isxd frames")
    isxd_times, annotations_times, annotations_mapped_frames = _map_frames(
        ref_recordings_times=isxd_recordings_times,
        align_recordings_times=annotations_recordings_times,
        ref_epoch_start_times=isxd_epoch_start_times,
        align_epoch_start_times=annotations_epoch_start_times,
    )

    logger.info("Generating output annotations")
    df = pd.concat(all_df, ignore_index=True)

    # TODO: add traces and status?
    # traces, status = _get_cellset_data(isxd_files)

    # create mapping of rows to corresponding element in input isxd series
    series = np.concatenate(
        [
            np.full((len(isxd_recordings_times[i]),), i, dtype=int)
            for i in range(len(isxd_recordings_times))
        ]
    )

    # construct vector of isxd recording times (i.e., no time delay between
    # isxd recordings in a series)
    time_offset = 0.0
    for i in range(len(isxd_recordings_times)):
        last_time = isxd_recordings_times[i].iloc[-1]
        isxd_recordings_times[i] += time_offset
        time_offset += last_time
    isxd_recordings_times = pd.concat(isxd_recordings_times, ignore_index=True)

    frame = np.arange(len(isxd_recordings_times))
    state = _map_defined_values_to_col(
        df=df,
        mapped_frames=annotations_mapped_frames,
        column_name=state_column,
    ).astype("category")
    if len(alignment_methods) == len(isxd_files):
        alignment_methods_by_series = alignment_methods
    else:
        alignment_methods_by_series = [alignment_methods[0]] * len(isxd_files)
    alignment_method = pd.Series(series).map(
        {
            series_idx: method
            for series_idx, method in enumerate(alignment_methods_by_series)
        }
    )
    new_df = pd.DataFrame(
        {
            "frame": frame,
            "series": series,
            "time": isxd_recordings_times,
            "time since start (s)": isxd_times,
            "mapped frame": annotations_mapped_frames.astype(pd.Int64Dtype()),
            "mapped time since start (s)": [
                np.nan if np.isnan(frame) else annotations_times[frame]
                for frame in annotations_mapped_frames
            ],
            ALIGNMENT_METHOD_COLUMN: alignment_method,
            "state": state,
        }
    )
    new_df = new_df.reset_index(drop=True)

    # get any extra columns
    logger.info("Extracting extra columns from input annotations")
    df_extra = pd.DataFrame()
    for column_name in df.columns:
        if column_name in [
            time_column,
            state_column,
            ALIGNMENT_METHOD_COLUMN,
        ]:
            continue
        df_extra[column_name] = _map_defined_values_to_col(
            df=df,
            mapped_frames=annotations_mapped_frames,
            column_name=column_name,
        )

    if not df_extra.empty:
        # add extra columns to new dataframe
        new_df = pd.concat([new_df, df_extra], axis=1)

    # save dataframe to parquet file
    logger.info("Saving output annotations to disk.")
    new_df.to_parquet(PARQUET_FILENAME)

    logger.info(
        f"Annotations data saved "
        f"({os.path.basename(PARQUET_FILENAME)}, "
        f"size: {get_file_size(PARQUET_FILENAME)})"
    )

    # make preview
    logger.info("Generating preview for output annotations.")
    _save_experiment_annotations_preview_and_metadata(
        PARQUET_FILENAME,
        PARQUET_PREVIEW_FILENAME,
        top_n_states=10,
    )

    logger.info("Data conversion completed")


@beartype
def sync_boris_to_annotations(
    *,
    cell_set_file: List[str],
    annotations_file: List[str],
    state_column_name: str = "Behavior",
    start_column_name: str = "Start (s)",
    stop_column_name: str = "Stop (s)",
    ignore_behaviors=("immobile", "rearing"),
) -> None:
    """Convert annotations file from epoch-based format to
    IDEAS standard format.

    Saves annotations to a column called "epoch"


    """
    # unpack list
    annotations_file = annotations_file[0]

    logger.info("Converting state-based annotations data to IDEAS format")

    # read time info from the input cell set file
    time = io.cell_set_to_time(cell_set_file)
    dt = time[1]  # time diff between consecutive samples

    # read in epoch-based  annotations file
    delimiter = "\t" if annotations_file.endswith(".tsv") else ","
    df = pd.read_csv(annotations_file, delimiter=delimiter)

    # check columns are valid
    _check_columns_in_df(
        df=df,
        columns=(
            state_column_name,
            start_column_name,
            stop_column_name,
        ),
    )

    # initialize arrays
    state = ["not_defined" for _ in time]

    # iterate over the rows of the input
    # annotations dataframe
    for _, row in df.iterrows():
        # convert start and stop time of behavior to indices
        #  in the cell set samples
        start_index = int(np.floor(row[start_column_name] / dt))
        end_index = int(np.floor(row[stop_column_name] / dt))

        if start_index > time.shape[0] or end_index > time.shape[0]:
            continue

        if row[state_column_name] in ignore_behaviors:
            continue

        # this is a behavior we want to make note of
        state[start_index:end_index] = [
            row[state_column_name] for _ in range(start_index, end_index)
        ]

    # convert behavior arrays to categorical variables
    state = pd.Series(state, dtype="category")
    frame = np.arange(len(time))
    # create output dataframe
    df = pd.DataFrame(
        dict(
            frame=frame,
            time=time,
            state=state,
        )
    )

    df.to_parquet(PARQUET_FILENAME)

    logger.info(
        f"Annotations data saved "
        f"({os.path.basename(PARQUET_FILENAME)}, "
        f"size: {get_file_size(PARQUET_FILENAME)})"
    )

    _save_experiment_annotations_preview_and_metadata(
        PARQUET_FILENAME,
        PARQUET_PREVIEW_FILENAME,
        top_n_states=10,
    )

    logger.info("Data conversion completed")
