name: pull-request

on:
  push:
    branches: ["main"]
  pull_request:
    # trigger all branches
jobs:
  pull-request-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13
        cache: 'pip'  # Cache pip dependencies
        cache-dependency-path: pyproject.toml
    - run: make venv
    - name: Check code formatting
      run: make ruff-check
    - name: Check unit tests
      run: make test
